### ISSUE TITLE
How to define schema for source code?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [quickwit-inc/tantivy-cli#75]
I have no prior experience with tantivy, and I want to use it to search a huge amount of source code (like the Chromium's repository). What's the proper way to define a schema for it? Thanks.

**Comment by fulmicoton** [comment]
I really depends on tiny details about the search experience you are trying to build.

You probably want one field for the source code. 
Index it with positions and make it stored.
You might want to have a custom tokenizer but to start the normal tokenizer should do the job.

You will also want a field for the filepath. Make it indexed and stored to.

Maybe add one field for the language.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the suggestion! I'll give it a try.
